let products=[];let pendingImageFile=null;let editingId=null;
const money=n=>'LKR '+Number(n||0).toLocaleString();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function app(){const {data:{session}}=await supabaseClient.auth.getSession();if(!session){loginScreen();return}const {data:profile}=await supabaseClient.from('profiles').select('role').eq('id',session.user.id).maybeSingle();if(profile?.role!=='admin'){await supabaseClient.auth.signOut();loginScreen('This account is not an admin account.');return}dashboard()}
function loginScreen(msg=''){document.getElementById('adminApp').innerHTML=`<div class="login-box"><img src="assets/logo.jpg" style="width:100px;background:#000"><h1>Admin Login</h1>${msg?`<p style="color:#b00">${esc(msg)}</p>`:''}<form class="form" onsubmit="event.preventDefault();loginAdmin()"><label>Email</label><input id="au" type="email" required><label>Password</label><input id="ap" type="password" required><button>Sign In</button></form></div>`}
async function loginAdmin(){const {error}=await supabaseClient.auth.signInWithPassword({email:au.value.trim(),password:ap.value});if(error)return alert(error.message);app()}
function dashboard(){document.getElementById('adminApp').innerHTML=`<div class="admin-wrap"><aside class="sidebar"><h2>LD Creation</h2><button class="side-btn active" onclick="show('dashboard',this)">Dashboard</button><button class="side-btn" onclick="show('products',this)">Products</button><button class="side-btn" onclick="show('orders',this)">Orders</button><button class="side-btn" onclick="show('customers',this)">Customers</button><button class="side-btn" onclick="logout()">Logout</button></aside><main class="admin-main" id="adminMain"></main></div>`;show('dashboard')}
async function show(type,btn){if(btn){document.querySelectorAll('.side-btn').forEach(x=>x.classList.remove('active'));btn.classList.add('active')}if(type==='dashboard'){const [{count:pc},{count:oc},{count:cc},{data:orders}]=await Promise.all([supabaseClient.from('products').select('*',{count:'exact',head:true}),supabaseClient.from('orders').select('*',{count:'exact',head:true}),supabaseClient.from('profiles').select('*',{count:'exact',head:true}),supabaseClient.from('orders').select('*').order('created_at',{ascending:false}).limit(8)]);document.getElementById('adminMain').innerHTML=`<div class="admin-title"><h1>Dashboard</h1></div><div class="stats"><div class="stat"><small>Products</small><strong>${pc||0}</strong></div><div class="stat"><small>Orders</small><strong>${oc||0}</strong></div><div class="stat"><small>Customers</small><strong>${cc||0}</strong></div><div class="stat"><small>Revenue</small><strong>${money((orders||[]).reduce((a,o)=>a+Number(o.total),0))}</strong></div></div><div class="panel"><h3>Recent Orders</h3>${orderTable(orders||[])}</div>`}
if(type==='products'){await loadProducts();document.getElementById('adminMain').innerHTML=`<div class="admin-title"><h1>Products</h1><button class="primary-btn" onclick="editProduct(null)">+ Add Product</button></div><div class="product-admin">${products.map(p=>`<div class="panel"><div class="product-img">${p.image_url?`<img class="thumb" src="${esc(p.image_url)}">`:'<div class="placeholder-art">LD</div>'}</div><h3>${esc(p.name)}</h3><small>${esc(p.category)} • ${money(p.price)}</small><div class="admin-actions" style="margin-top:12px"><button class="small-btn" onclick="editProduct('${p.id}')">Edit</button><button class="small-btn danger" onclick="deleteProduct('${p.id}')">Delete</button></div></div>`).join('')}</div>`}
if(type==='orders'){const {data:orders}=await supabaseClient.from('orders').select('*').order('created_at',{ascending:false});document.getElementById('adminMain').innerHTML=`<div class="admin-title"><h1>Orders</h1></div><div class="panel">${orderTable(orders||[],true)}</div>`}
if(type==='customers'){const {data:users}=await supabaseClient.from('profiles').select('*').order('created_at',{ascending:false});document.getElementById('adminMain').innerHTML=`<div class="admin-title"><h1>Customers</h1></div><div class="panel"><div class="table-wrap"><table class="data-table"><tr><th>Name</th><th>Email</th><th>Mobile</th><th>Role</th></tr>${(users||[]).map(u=>`<tr><td>${esc(u.full_name)}</td><td>${esc(u.email)}</td><td>${esc(u.mobile||'-')}</td><td>${esc(u.role)}</td></tr>`).join('')}</table></div></div>`}}
async function loadProducts(){const {data,error}=await supabaseClient.from('products').select('*').order('created_at',{ascending:false});if(error)return alert(error.message);products=data||[]}
function orderTable(os,full=false){if(!os.length)return '<p style="color:#888">No orders yet.</p>';return `<div class="table-wrap"><table class="data-table"><tr><th>Order</th><th>Customer</th><th>Items</th><th>Total</th><th>Status</th>${full?'<th>Details</th>':''}</tr>${os.map(o=>`<tr><td>${esc(o.order_no)}<br><small>${new Date(o.created_at).toLocaleString()}</small></td><td>${esc(o.customer_name)}<br>${esc(o.mobile)}</td><td><button class="small-btn" onclick="viewOrder('${o.id}')">View items</button></td><td>${money(o.total)}</td><td><select onchange="updateStatus('${o.id}',this.value)">${['Pending','Confirmed','Processing','Delivered','Cancelled'].map(s=>`<option ${o.status===s?'selected':''}>${s}</option>`).join('')}</select></td>${full?`<td><button class="small-btn" onclick="viewOrder('${o.id}')">View</button></td>`:''}</tr>`).join('')}</table></div>`}
async function updateStatus(id,status){const {error}=await supabaseClient.from('orders').update({status}).eq('id',id);if(error)alert(error.message)}
async function viewOrder(id){const {data:o}=await supabaseClient.from('orders').select('*').eq('id',id).single();const {data:items}=await supabaseClient.from('order_items').select('*').eq('order_id',id);if(!o)return;alert(`Order: ${o.order_no}\nCustomer: ${o.customer_name}\nMobile: ${o.mobile}\nAddress: ${o.address}\nPayment: ${o.payment_method}\nStatus: ${o.status}\n\nProducts:\n${(items||[]).map(i=>i.product_name+' x '+i.quantity+' = '+money(i.unit_price*i.quantity)).join('\n')}\n\nTotal: ${money(o.total)}`)}
function editProduct(id){editingId=id;const p=id?products.find(x=>x.id===id):{name:'',category:'Abstract',price:0,description:'',image_url:''};pendingImageFile=null;document.getElementById('adminMain').innerHTML=`<div class="admin-title"><h1>${id?'Edit':'Add'} Product</h1></div><div class="panel"><form class="form" onsubmit="event.preventDefault();saveProduct()"><label>Product name</label><input id="pn" value="${esc(p.name)}" required><label>Category</label><select id="pc"><option ${p.category==='Abstract'?'selected':''}>Abstract</option><option ${p.category==='Nature'?'selected':''}>Nature</option><option ${p.category==='Minimal'?'selected':''}>Minimal</option></select><label>Price (LKR)</label><input id="pp" type="number" min="0" value="${p.price}" required><label>Description</label><textarea id="pd" rows="4">${esc(p.description)}</textarea><label>Product image</label><input id="pifile" type="file" accept="image/png,image/jpeg,image/webp" onchange="pendingImageFile=this.files[0]||null"><small>Upload JPG, PNG or WebP. Maximum 8MB.</small><div class="upload-preview">${p.image_url?`<img src="${esc(p.image_url)}" alt="Current product image">`:'<div class="upload-placeholder">No image selected</div>'}</div><button>Save Product</button></form></div>`}
async function saveProduct(){let name=pn.value.trim(),price=Number(pp.value);if(!name||!price)return alert('Please enter product name and price.');let image_url=editingId?(products.find(x=>x.id===editingId)?.image_url||''):'';if(pendingImageFile){if(pendingImageFile.size>8*1024*1024)return alert('Please choose an image smaller than 8MB.');const ext=(pendingImageFile.name.split('.').pop()||'jpg').toLowerCase();const path=`${crypto.randomUUID()}.${ext}`;const {error:ue}=await supabaseClient.storage.from('product-images').upload(path,pendingImageFile,{upsert:false,contentType:pendingImageFile.type});if(ue)return alert(ue.message);const {data:pub}=supabaseClient.storage.from('product-images').getPublicUrl(path);image_url=pub.publicUrl}
const payload={name,category:pc.value,price,description:pd.value.trim(),image_url,active:true};let res=editingId?await supabaseClient.from('products').update(payload).eq('id',editingId):await supabaseClient.from('products').insert(payload);if(res.error)return alert(res.error.message);editingId=null;pendingImageFile=null;show('products')}
async function deleteProduct(id){if(!confirm('Delete this product?'))return;const {error}=await supabaseClient.from('products').delete().eq('id',id);if(error)return alert(error.message);show('products')}
async function logout(){await supabaseClient.auth.signOut();loginScreen()}
app();
