let products=[]; let cart=JSON.parse(localStorage.getItem('ld_cart')||'[]'); let activeCat='All';
const money=n=>'LKR '+Number(n||0).toLocaleString();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function saveCart(){localStorage.setItem('ld_cart',JSON.stringify(cart));document.getElementById('cartCount').textContent=cart.reduce((a,b)=>a+b.qty,0)}
async function loadProducts(){const {data,error}=await supabaseClient.from('products').select('*').eq('active',true).order('created_at',{ascending:false});if(error){console.error(error);document.getElementById('products').innerHTML='<p>Products could not be loaded. Please check the Supabase setup.</p>';return}products=data||[];renderProducts()}
function renderProducts(){const el=document.getElementById('products');const list=activeCat==='All'?products:products.filter(p=>p.category===activeCat);if(!list.length){el.innerHTML='<p>No products available in this category.</p>';return}el.innerHTML=list.map(p=>`<article class="product"><div class="product-img">${p.image_url?`<img src="${esc(p.image_url)}" alt="${esc(p.name)}">`:'<div class="placeholder-art">LD</div>'}</div><div class="product-body"><div class="product-cat">${esc(p.category)}</div><h3>${esc(p.name)}</h3><div class="price">${money(p.price)}</div><button class="add" onclick="addToCart('${p.id}')">Add to Cart</button></div></article>`).join('')}
function addToCart(id){let x=cart.find(i=>i.id===id);x?x.qty++:cart.push({id,qty:1});saveCart();openCart()}
function getCartProducts(){return cart.map(i=>({line:i,p:products.find(p=>p.id===i.id)})).filter(x=>x.p)}
function openCart(){document.getElementById('modal').classList.remove('hidden');const el=document.getElementById('modalContent');const rows=getCartProducts();if(!rows.length){el.innerHTML='<button class="close" onclick="closeModal()">×</button><h2>Your Cart</h2><div class="empty">Your cart is empty.</div>';return}let total=rows.reduce((s,x)=>s+x.p.price*x.line.qty,0);el.innerHTML=`<button class="close" onclick="closeModal()">×</button><h2>Your Cart</h2>${rows.map(x=>`<div class="cart-row"><div class="mini-img">${x.p.image_url?`<img src="${esc(x.p.image_url)}">`:'<div class="placeholder-art" style="width:70px;height:70px;font-size:24px">LD</div>'}</div><div><strong>${esc(x.p.name)}</strong><div>${money(x.p.price)}</div><div class="qty"><button onclick="changeQty('${x.p.id}',-1)">−</button>${x.line.qty}<button onclick="changeQty('${x.p.id}',1)">+</button></div></div><button class="small-btn danger" onclick="removeCart('${x.p.id}')">Remove</button></div>`).join('')}<div class="total"><span>Total</span><span>${money(total)}</span></div><button class="form button" style="width:100%;background:#111;color:#fff;border:0;padding:13px;cursor:pointer" onclick="checkout()">Proceed to Checkout</button>`}
function changeQty(id,n){let x=cart.find(i=>i.id===id);if(!x)return;x.qty+=n;if(x.qty<1)cart=cart.filter(i=>i.id!==id);saveCart();openCart()}
function removeCart(id){cart=cart.filter(i=>i.id!==id);saveCart();openCart()}
function closeModal(){document.getElementById('modal').classList.add('hidden')}
async function login(){document.getElementById('modal').classList.remove('hidden');document.getElementById('modalContent').innerHTML='<button class="close" onclick="closeModal()">×</button><h2>Customer Login</h2><form class="form" onsubmit="event.preventDefault();doLogin()"><label>Email</label><input id="email" type="email" required><label>Password</label><input id="password" type="password" required><button>Login</button></form><p style="font-size:13px;color:#777">New customer? <a href="#" onclick="register();return false">Create an account</a></p>'}
function register(){document.getElementById('modalContent').innerHTML='<button class="close" onclick="closeModal()">×</button><h2>Create Account</h2><form class="form" onsubmit="event.preventDefault();doRegister()"><label>Full name</label><input id="rname" required><label>Email</label><input id="remail" type="email" required><label>Mobile</label><input id="rmobile" required><label>Password</label><input id="rpass" type="password" minlength="6" required><button>Create Account</button></form>'}
async function doRegister(){const name=rname.value.trim(),email=remail.value.trim(),mobile=rmobile.value.trim(),password=rpass.value;const {data,error}=await supabaseClient.auth.signUp({email,password});if(error)return alert(error.message);if(data.user){const {error:pe}=await supabaseClient.from('profiles').upsert({id:data.user.id,full_name:name,mobile,email});if(pe)console.error(pe)}alert('Account created. If email confirmation is enabled, please confirm your email first.');closeModal()}
async function doLogin(){const {error}=await supabaseClient.auth.signInWithPassword({email:email.value.trim(),password:password.value});if(error)return alert(error.message);closeModal();alert('Login successful.')}
async function checkout(){const {data:{user}}=await supabaseClient.auth.getUser();if(!user){login();return}const {data:profile}=await supabaseClient.from('profiles').select('*').eq('id',user.id).maybeSingle();document.getElementById('modalContent').innerHTML=`<button class="close" onclick="closeModal()">×</button><h2>Checkout</h2><form class="form" onsubmit="event.preventDefault();placeOrder()"><label>Full name</label><input id="cname" value="${esc(profile?.full_name||'')}" required><label>Mobile number</label><input id="cmobile" value="${esc(profile?.mobile||'')}" required><label>Delivery address</label><textarea id="caddress" rows="4" required></textarea><label>Payment method</label><select id="cpayment"><option>Cash on Delivery</option><option>Bank Transfer</option></select><button>Place Order</button></form>`}
async function placeOrder(){const rows=getCartProducts();if(!rows.length)return alert('Your cart is empty.');const {data:{user}}=await supabaseClient.auth.getUser();if(!user)return login();const total=rows.reduce((s,x)=>s+x.p.price*x.line.qty,0);const {data:order,error:oe}=await supabaseClient.from('orders').insert({user_id:user.id,customer_name:cname.value.trim(),mobile:cmobile.value.trim(),address:caddress.value.trim(),payment_method:cpayment.value,total,status:'Pending'}).select().single();if(oe)return alert(oe.message);const items=rows.map(x=>({order_id:order.id,product_id:x.p.id,product_name:x.p.name,unit_price:x.p.price,quantity:x.line.qty}));const {error:ie}=await supabaseClient.from('order_items').insert(items);if(ie){await supabaseClient.from('orders').delete().eq('id',order.id);return alert(ie.message)}await supabaseClient.from('profiles').update({full_name:cname.value.trim(),mobile:cmobile.value.trim()}).eq('id',user.id);cart=[];saveCart();closeModal();alert('Order placed successfully. Your order number is '+order.order_no+'.')}
document.getElementById('cartBtn').onclick=openCart;document.getElementById('loginBtn').onclick=login;document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeCat=b.dataset.cat;renderProducts()});document.getElementById('modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});saveCart();loadProducts();
